#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
ENV_FILE="$ROOT/.env"
UID_STRING="Sergio Peschiera (VOCO releases) <speschiera@gmail.com>"
KEYS_FILE="$ROOT/KEYS"

banner "VOCO release signing"

# ── 1. Create a local GPG signing key (never stored in git or CI) ─────────
stage "Create GPG signing key"
say "This key stays on this machine. It is not uploaded to GitHub Actions."
say "Hosted NVIDIA builds stay disabled; you sign tags and checksums locally."
warn "Do not use the OpenClaw VPS SSH key. Do not paste the private key anywhere."
if ! command -v gpg >/dev/null 2>&1; then
  warn "gpg is not installed. Install gnupg and re-run this wizard."
  exit 1
fi
EXISTING_FPR=""
if EXISTING_FPR=$(gpg --batch --list-secret-keys --with-colons "$UID_STRING" 2>/dev/null | awk -F: '$1=="fpr" {print $10; exit}'); then
  :
fi
if [[ -n "${EXISTING_FPR}" ]]; then
  note "A secret key for $UID_STRING already exists."
  note "Fingerprint: $EXISTING_FPR"
  GPG_KEY_FINGERPRINT="$EXISTING_FPR"
else
  step "Choose a strong passphrase you will not store in this repo, chat, or CI."
  ask_secret GPG_PASSPHRASE "New key passphrase:"
  ask_secret GPG_PASSPHRASE_AGAIN "Repeat passphrase:"
  if [[ -z "$GPG_PASSPHRASE" ]]; then
    warn "A passphrase is required. Empty passphrases are not accepted."
    exit 1
  fi
  if [[ "$GPG_PASSPHRASE" != "$GPG_PASSPHRASE_AGAIN" ]]; then
    warn "Passphrases did not match. Nothing was generated."
    exit 1
  fi
  unset GPG_PASSPHRASE_AGAIN
  say "Generating an ed25519 signing key that expires in 2 years…"
  # Passphrase on a dedicated fd, never in argv or a here-string file.
  exec 3< <(printf '%s\n' "$GPG_PASSPHRASE")
  gpg --batch --yes --pinentry-mode loopback --passphrase-fd 3 \
    --quick-generate-key "$UID_STRING" ed25519 sign 2y
  exec 3<&-
  unset GPG_PASSPHRASE
  GPG_KEY_FINGERPRINT=$(gpg --batch --list-secret-keys --with-colons "$UID_STRING" | awk -F: '$1=="fpr" {print $10; exit}')
  if [[ -z "$GPG_KEY_FINGERPRINT" ]]; then
    warn "Key generation did not produce a fingerprint."
    exit 1
  fi
  say "Key created. Fingerprint: $GPG_KEY_FINGERPRINT"
  note "gpg also wrote a revocation certificate under ~/.gnupg/openpgp-revocs.d/"
  note "Back up that revocation file and the private key offline. Do not commit them."
fi
write_env GPG_KEY_FINGERPRINT "$GPG_KEY_FINGERPRINT"
pause "Continue to export the public key?"

# ── 2. Export public key into KEYS (public; no private material) ──────────
stage "Export public key"
say "KEYS in the repository is the public signing key only."
step "Exporting $GPG_KEY_FINGERPRINT to KEYS"
{
  printf '%s\n' \
    "# VOCO release signing key" \
    "# User ID: $UID_STRING" \
    "# Fingerprint: $GPG_KEY_FINGERPRINT" \
    "# Verify this fingerprint out of band before importing KEYS from a clone." \
    "# Do not append unrelated keys to this file." \
    ""
  gpg --batch --armor --export "$GPG_KEY_FINGERPRINT"
} > "$KEYS_FILE"
chmod 644 "$KEYS_FILE"
if grep -q "BEGIN PGP PRIVATE KEY" "$KEYS_FILE"; then
  rm -f "$KEYS_FILE"
  warn "Refusing to write a private key into KEYS."
  exit 1
fi
say "Wrote public key to KEYS"
note "Commit KEYS only after you have checked it contains no private key block."
pause "Continue to add the public key on GitHub?"

# ── 3. GitHub signing key (browser; token may lack gpg_key scope) ─────────
stage "Add the public key on GitHub"
say "GitHub shows a Verified badge on tags signed with this key."
open_url "https://github.com/settings/gpg/new"
step "Title: VOCO releases"
step "Open KEYS, copy only the ASCII-armored public block (BEGIN through END)."
step "Paste it into GitHub → Settings → SSH and GPG keys → New GPG key."
step "Do not upload a private key. Do not create a GitHub Actions secret for this key."
pause "Press Enter after GitHub shows the key."

# ── 4. Local git config for this repository only ──────────────────────────
stage "Configure git tag signing"
say "Signing is enabled for this VOCO clone only, not every git repo on the machine."
git config --local user.signingkey "$GPG_KEY_FINGERPRINT"
git config --local tag.gpgSign true
git config --local gpg.format openpgp
note "commit.gpgsign is left off; this wizard signs tags, not every commit."
say "Configured user.signingkey=$GPG_KEY_FINGERPRINT and tag.gpgSign=true"
pause "Continue to the no-retag confirmation?"

# ── 5. Never move the public unsigned tag ─────────────────────────────────
stage "Do not retag 2026.0.39"
say "voco.2026.0.39 at fb957ff is a frozen unsigned public tag."
warn "Never run: git tag -d voco.2026.0.39"
warn "Never run: git push --force origin voco.2026.0.39"
warn "Never recreate that tag with a signature."
say "Checksums for 2026.0.39 remain integrity checks, not a publisher signature."
if ! confirm "I will leave voco.2026.0.39 unchanged"; then
  warn "Stopped. The unsigned public tag must stay frozen."
  exit 1
fi

# ── 6. Next cut only (no release is created now) ──────────────────────────
stage "Next signed release"
say "When you cut the next version, from a clean verified tree:"
step "git tag -s voco.<version> -m \"VOCO <version>\""
step "git tag -v voco.<version>"
step "gpg --detach-sign --armor voco_<version>_checksums.txt"
step "gpg --detach-sign --armor voco_latest_checksums.txt"
step "Attach both .txt and .asc files to the GitHub release"
step "bash scripts/verify-release.sh --keys KEYS voco_<version>_checksums.txt"
note "scripts/sign-release-checksums.sh wraps the detach-sign step."
note "The hosted Release workflow must still not assemble NVIDIA installers or hold this key."
pause "Press Enter to finish."

finish
